<?php
$this->css($this->assetModule('script/user-ui.css'));
?>
<ul class="nav nav-tabs">
    <li class="active">
        <a href="<?php echo $this->url('admin', array('controller' => 'account', 'action' => 'index'));?>">
            <?php _e('User');?>
        </a>
    </li>
    <li class="">
        <a href="<?php echo $this->url('admin', array('controller' => 'custom', 'action' => 'register.complete'));?>">
            <?php _e('Unactivated');?>
        </a>
    </li>
    <li class="">
        <a href="<?php echo $this->url('admin', array('controller' => 'custom', 'action' => 'profile.edit'));?>">
            <?php _e('Banned');?>
        </a>
    </li>
    <li class="">
        <a href="<?php echo $this->url('admin', array('controller' => 'custom', 'action' => 'profile.edit'));?>">
            <?php _e('Deleted');?>
        </a>
    </li>
    <li class="">
        <a href="<?php echo $this->url('admin', array('controller' => 'custom', 'action' => 'profile.edit'));?>">
            <?php _e('Add user');?>
        </a>
    </li>
</ul>

<table class="table table-striped">
    <tbody>
        <tr>
            <th><?php _e('UID');?></th>
            <th><?php _e('Username');?></th>
            <th><?php _e('Email');?></th>
            <th><?php _e('User role');?></th>
            <th><?php _e('Staff role');?></th>
            <th><?php _e('Register ip');?></th>
            <th><?php _e('Register time');?></th>
        </tr>
        <?php foreach ($users as $id => $user) { ?>
        <tr>
            <td>
                <input type="checkbox" class="check-one" value="<?php echo $user['id']; ?>">
            </td>
            <td>
                <?php echo $this->escape($user['id']);?>
            </td>
            <td>
                <?php echo $this->escape($user['identity']);?>
                <div class="row-actions">
                    <a href="<?php echo $this->url('', array('action' => 'edit', 'id' => $user['id'])); ?>" title="<?php _e('Edit'); ?>"><?php _e('Edit'); ?></a>
                    <span class="divider">|</span>
                    <a href="<?php echo $this->url('', array('action' => 'role', 'id' => $user['id'])); ?>" title="<?php _e('Role'); ?>"><?php _e('Role'); ?></a>
                    <span class="divider">|</span>
                    <a href="<?php echo $this->url('', array('action' => 'password', 'id' => $user['id'])); ?>" title="<?php _e('Password'); ?>"><?php _e('Password'); ?></a>
                    <span class="divider">|</span>
                    <a href="<?php echo $this->url('', array('action' => 'ban', 'id' => $user['id'])); ?>" title="<?php _e('Ban'); ?>"><?php _e('Ban'); ?></a>
                    <span class="divider">|</span>
                    <a href="<?php echo $this->url('', array('action' => 'delete', 'id' => $user['id'])); ?>" title="<?php _e('Delete'); ?>"><?php _e('Delete'); ?></a>
                </div>
            </td>
            <td><?php echo $this->escape($user['email']); ?></td>
            <td><?php echo $this->escape($user['role']); ?></td>
            <td><?php echo $this->escape($user['role_staff']); ?></td>
            <td><?php echo $this->escape($user['register_ip']); ?></td>
            <td><?php echo $this->escape(_date($user['time_register'])); ?></td>
        </tr>
        <?php } ?>
    </tbody>
</table>

<input type="checkbox" class="check-all"><span><?php _e('Check all');?></span>

<?php echo $this->paginationControl($paginator, 'Sliding', 'paginator.phtml'); ?>