<?php
$this->css($this->assetModule('script/user-ui.css'));
$this->jQuery();
?>
<ul class="nav nav-tabs">
    <li class="active">
        <a href="<?php echo $this->url('admin', array('controller' => 'account', 'action' => 'index'));?>">
            <?php _e('User');?>
        </a>
    </li>
    <li class="">
        <a href="<?php echo $this->url('admin', array('controller' => 'account', 'action' => 'pending'));?>">
            <?php _e('Pending');?>
        </a>
    </li>
    <li class="">
        <a href="<?php echo $this->url('admin', array('controller' => 'account', 'action' => 'banned'));?>">
            <?php _e('Banned');?>
        </a>
    </li>
    <li class="">
        <a href="<?php echo $this->url('admin', array('controller' => 'account', 'action' => 'deleted'));?>">
            <?php _e('Deleted');?>
        </a>
    </li>
    <li class="">
        <a href="<?php echo $this->url('admin', array('controller' => 'custom', 'action' => 'profile.edit'));?>">
            <?php _e('Add user');?>
        </a>
    </li>
</ul>
<form method="post" id="account" action="<?php echo $this->url('admin', array('controller' => 'account', 'action' => 'manage'))?>" >
<table class="table table-striped">
    <tbody>
        <tr>
            <th><?php _e('UID');?></th>
            <th><?php _e('Username');?></th>
            <th><?php _e('Email');?></th>
            <th><?php _e('User role');?></th>
            <th><?php _e('Staff role');?></th>
            <th><?php _e('Register ip');?></th>
            <th><?php _e('Register time');?></th>
        </tr>
        <?php foreach ($users as $id => $user) { ?>
        <tr>
            <td>
                <input type="checkbox" value="<?php echo $user['id']?>" name="check-one">
                <?php echo $this->escape($user['id']);?>
            </td>
            <td>
                <?php echo $this->escape($user['identity']);?>
                <?php $redirect = urlencode($this->url('admin', array('controller' => 'account', 'action' => 'index'))); ?>
                <div class="row-actions">
                    <a href="<?php echo $this->url('', array('action' => 'edit', 'id' => $user['id'], 'redirect' => $redirect)); ?>" title="<?php _e('Edit'); ?>"><?php _e('Edit'); ?></a>
                    <span class="divider">|</span>
                    <a href="<?php echo $this->url('', array('action' => 'role', 'id' => $user['id'], 'redirect' => $redirect)); ?>" title="<?php _e('Role'); ?>"><?php _e('Role'); ?></a>
                    <span class="divider">|</span>
                    <a href="<?php echo $this->url('', array('action' => 'password', 'id' => $user['id'], 'redirect' => $redirect)); ?>" title="<?php _e('Password'); ?>"><?php _e('Password'); ?></a>
                    <span class="divider">|</span>
                    <a href="<?php echo $this->url('', array('action' => 'ban', 'id' => $user['id'], 'redirect' => $redirect)); ?>" title="<?php _e('Ban'); ?>"><?php _e('Ban'); ?></a>
                    <span class="divider">|</span>
                    <a href="<?php echo $this->url('', array('action' => 'delete', 'id' => $user['id'], 'redirect' => $redirect)); ?>" title="<?php _e('Delete'); ?>"><?php _e('Delete'); ?></a>
                </div>
            </td>
            <td><?php echo $this->escape($user['email']); ?></td>
            <td><?php echo $this->escape($user['role']); ?></td>
            <td><?php echo $this->escape($user['role_staff']); ?></td>
            <td><?php echo $this->escape($user['register_ip']); ?></td>
            <td><?php echo $this->escape(_date($user['time_register'])); ?></td>
        </tr>
        <?php } ?>
    </tbody>
</table>
<?php if ($users) { ?>
<div>
    <input type="checkbox" name="check-all"><span>&nbsp;&nbsp;&nbsp;</span><span><?php _e('Select all');?></span><span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span>
    <select id="operate-select">
        <option value="operation"><?php _e('Operation'); ?></option>
        <option value="ban"><?php _e('Ban'); ?></option>
        <option value="delete"><?php _e('Delete'); ?></option>
        <option value="role"><?php _e('Assign role'); ?></option>
    </select>
</div>
<?php } ?>
<input type="hidden" name="type">
<input type="hidden" name="ids">
</form>
<?php echo $this->paginationControl($paginator, 'Sliding', 'paginator.phtml'); ?>

<script>
    $("document").ready(function(){
        $("[name='check-all']").click(function(){console.log($(this).prop("checked"));
            if($(this).prop("checked")){
                $("[name='check-one']").prop('checked', true);
            }else{
                $("[name='check-one']").prop('checked', false);
            }
        });

        $("#operate-select").change(function(){
            if ($(this).val()!='operation') {
                var ids='';
                $("[name='check-one']:checked").each(function(){
                    ids+=$(this).val()+',';
                });

                if(ids  && confirm('Sure ' + $(this).val() + '?')) {
                    $("[name='type']").val($(this).val());
                    $("[name='ids']").val(ids);
                    $("#account").submit();
                }
            }
        });
    });
</script>
