<?php
$this->jQuery();
$this->bootstrap(array('datepicker/datepicker.css',
    'datepicker/bootstrap-datepicker.js'));
?>
<!--<div class="input-append date" id="dp3" data-date="12-02-2012" data-date-format="dd-mm-yyyy">-->
<!--    <input class="span2" size="16" type="text" value="12-02-2012">-->
<!--    <span class="add-on"><i class="icon-th"></i></span>-->
<!--</div>-->
<form method="post">
    <input  name="bit" class="datepicker" type="text">
    <input type="submit" value="submit">
</form>

<script>
    $('.datepicker').datepicker();
</script>